builds:
  - binary: atlas
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/MohamedBeydoun/atlas/cmd.version={{.Env.ATLAS_VERSION}}