name: Release

# on:
#   push:
#     branches:
#       - master
on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: master

    - name: Install dependencies
      run: |
        go mod vendor
        git branch -a

    # - name: Release
    #   run: |
    #     make release